# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

job_defaults: &defaults
    docker:
      - image: frolvlad/alpine-bash
    working_directory: ~/repo
    environment:
      ENVIRONMENT: "test"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: ./test/runner

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
